/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Hydra
 */
public class AdministracionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public AdministracionAdmin() {
        initComponents();
    }

    public static void main(String[] args) {
        AdministracionAdmin a = new AdministracionAdmin();
        a.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnlAdministracion = new javax.swing.JTabbedPane();
        pnlClientes = new ventanas.PanelClientes();
        pnlInfoVentas = new ventanas.PanelInfoVentas();
        pnlInventario = new ventanas.PanelInventario();
        pnlProductos = new ventanas.PanelProductos();
        pnlVenta = new ventanas.panelVenta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        tpnlAdministracion.addTab("Clientes", pnlClientes);

        pnlInfoVentas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlInfoVentas.setMinimumSize(new java.awt.Dimension(795, 600));
        pnlInfoVentas.setPreferredSize(new java.awt.Dimension(795, 600));
        tpnlAdministracion.addTab("InfoVentas", pnlInfoVentas);

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        tpnlAdministracion.addTab("Inventario", pnlInventario);

        pnlProductos.setMinimumSize(new java.awt.Dimension(700, 500));
        pnlProductos.setPreferredSize(new java.awt.Dimension(795, 595));

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        tpnlAdministracion.addTab("Productos", pnlProductos);

        pnlVenta.setLayout(new java.awt.GridBagLayout());
        tpnlAdministracion.addTab("Ventas", pnlVenta);

        getContentPane().add(tpnlAdministracion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ventanas.PanelClientes pnlClientes;
    private ventanas.PanelInfoVentas pnlInfoVentas;
    private ventanas.PanelInventario pnlInventario;
    private ventanas.PanelProductos pnlProductos;
    private ventanas.panelVenta pnlVenta;
    private javax.swing.JTabbedPane tpnlAdministracion;
    // End of variables declaration//GEN-END:variables
}
