/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Hydra
 */
public class AdministracionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionUsuario
     */
    public AdministracionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCompra1 = new ventanas.PanelCompra();
        panelDesign1 = new ventanas.PanelDesign();
        panelCuenta1 = new ventanas.PanelCuenta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCompra1Layout = new javax.swing.GroupLayout(panelCompra1);
        panelCompra1.setLayout(panelCompra1Layout);
        panelCompra1Layout.setHorizontalGroup(
            panelCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelCompra1Layout.setVerticalGroup(
            panelCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Compra", panelCompra1);

        javax.swing.GroupLayout panelDesign1Layout = new javax.swing.GroupLayout(panelDesign1);
        panelDesign1.setLayout(panelDesign1Layout);
        panelDesign1Layout.setHorizontalGroup(
            panelDesign1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelDesign1Layout.setVerticalGroup(
            panelDesign1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Design", panelDesign1);

        javax.swing.GroupLayout panelCuenta1Layout = new javax.swing.GroupLayout(panelCuenta1);
        panelCuenta1.setLayout(panelCuenta1Layout);
        panelCuenta1Layout.setHorizontalGroup(
            panelCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        panelCuenta1Layout.setVerticalGroup(
            panelCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cuenta", panelCuenta1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private ventanas.PanelCompra panelCompra1;
    private ventanas.PanelCuenta panelCuenta1;
    private ventanas.PanelDesign panelDesign1;
    // End of variables declaration//GEN-END:variables
}
