/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author MEMO0464
 */
public class PaneldePago extends javax.swing.JFrame {

    /**
     * Creates new form PaneldePago
     */
    public PaneldePago() {
        initComponents();
        RestrictedTextField r = new RestrictedTextField(txtNumeroT);
        r.setLimit(16);
        RestrictedTextField m = new RestrictedTextField(txtMes);
        m.setLimit(2);
        RestrictedTextField a = new RestrictedTextField(txtAno);
        a.setLimit(2);
        RestrictedTextField c = new RestrictedTextField(txtCS);
        c.setLimit(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPago = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCS = new javax.swing.JTextField();
        cmbTtarjeta = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        pnlExpi = new javax.swing.JPanel();
        txtMes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(122, 108, 105));

        pnlPago.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Codigo de Seguridad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(jLabel5, gridBagConstraints);

        txtNombreT.setText("NOMBRE");
        txtNombreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTActionPerformed(evt);
            }
        });
        txtNombreT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(txtNombreT, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del Titular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(jLabel1, gridBagConstraints);

        txtNumeroT.setText("NUMER");
        txtNumeroT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(txtNumeroT, gridBagConstraints);

        jLabel2.setText("Número de Tarjeta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(jLabel2, gridBagConstraints);

        jLabel4.setText("Fecha de Expiración");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(jLabel4, gridBagConstraints);

        txtCS.setText("COD");
        txtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSActionPerformed(evt);
            }
        });
        txtCS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCSKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(txtCS, gridBagConstraints);

        cmbTtarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Visa", "MasterCard", "AMERICAN " }));
        cmbTtarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTtarjetaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(cmbTtarjeta, gridBagConstraints);

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 2, 11, 0);
        pnlPago.add(btnPagar, gridBagConstraints);

        txtMes.setText("MES");
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        pnlExpi.add(txtMes);

        jLabel3.setText("/");
        pnlExpi.add(jLabel3);

        txtAno.setText("ANO");
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoKeyTyped(evt);
            }
        });
        pnlExpi.add(txtAno);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlPago.add(pnlExpi, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnlPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(pnlPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTActionPerformed

    }//GEN-LAST:event_txtNombreTActionPerformed

    private void txtNombreTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTKeyTyped
        char c= evt.getKeyChar();
        if((c<'a'||c>'z') && (c<'A'||c>'Z')&& ( c != ' ')){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreTKeyTyped

    private void txtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSActionPerformed

    private void txtNumeroTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTKeyTyped
       char validar = evt.getKeyChar();
        if((validar<'0'||validar>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroTKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
         char validar = evt.getKeyChar();
        if((validar<'0'||validar>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyTyped
         char validar = evt.getKeyChar();
        if((validar<'0'||validar>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoKeyTyped

    private void txtCSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCSKeyTyped
        char validar = evt.getKeyChar();
        if((validar<'0'||validar>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtCSKeyTyped

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        FileOutputStream fbs;
        java.util.Date an = new Date();
        
        datosg();
        int t=cmbTtarjeta.getSelectedIndex();
        datos[4]=cmbTtarjeta.getItemAt(t);
        String vali[]=new String[2];
        vali[0]=txtMes.getText();
        vali[1]=txtAno.getText();
        fecha=Integer.parseInt(vali[0]);
        ano=Integer.parseInt(vali[1]);
        datos[2]=fecha+"/"+ano;
        
        if( t==0 ||datos[0].length()<5 || datos[1].length()<16 || datos[2].length()<4 || datos[3].length()<3 || fecha<0 && fecha>12 || ano<21){
            
            showMessageDialog(this,"Error verifica que todos los campos esten llenos correctamente");
           
        }else{
        
            try {
             fbs = new java.io.FileOutputStream("ListadePagos.tsp");
                java.io.DataOutputStream fds=new java.io.DataOutputStream(fbs);
                for(int i=0; i<5; i++){
                    fds.writeUTF(datos[i]);
                    
                    
             }
                fds.writeUTF("\n");
                fds.close();
         } catch (FileNotFoundException ex) {
                Logger.getLogger(PaneldePago.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
               Logger.getLogger(PaneldePago.class.getName()).log(Level.SEVERE, null, ex);
            }
       }   
    }//GEN-LAST:event_btnPagarActionPerformed

    private void cmbTtarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTtarjetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTtarjetaMouseClicked
    
    private void datosg(){
        
        
        datos[0]=txtNombreT.getText();
        datos[1]=txtNumeroT.getText();
        
        
        datos[3]=txtCS.getText();
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaneldePago().setVisible(true);
            }
        });
    }
    String datos[]=new String [5];
    
    int fecha=0;
    int ano=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cmbTtarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlExpi;
    private javax.swing.JPanel pnlPago;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCS;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombreT;
    private javax.swing.JTextField txtNumeroT;
    // End of variables declaration//GEN-END:variables
}
