/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author MEMO0464
 */
public class PaneldePago extends javax.swing.JFrame {

    /**
     * Creates new form PaneldePago
     */
    public PaneldePago() {
        initComponents();
        RestrictedTextField r = new RestrictedTextField(txtNumeroT);
        r.setLimit(16);
        RestrictedTextField m = new RestrictedTextField(txtMes);
        m.setLimit(2);
        RestrictedTextField a = new RestrictedTextField(txtAno);
        a.setLimit(2);
        RestrictedTextField c = new RestrictedTextField(txtCS);
        c.setLimit(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPago = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCS = new javax.swing.JTextField();
        cmbTtarjeta = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        pnlExpi = new javax.swing.JPanel();
        txtMes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(122, 108, 105));

        jPanel1.setBackground(new java.awt.Color(122, 108, 105));
        jPanel1.setForeground(new java.awt.Color(122, 108, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPago.setBackground(new java.awt.Color(122, 108, 105));
        pnlPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Codigo de Seguridad");
        pnlPago.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 203, 139, 24));

        txtNombreT.setText("NOMBRE");
        txtNombreT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTMouseClicked(evt);
            }
        });
        txtNombreT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTActionPerformed(evt);
            }
        });
        txtNombreT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTKeyTyped(evt);
            }
        });
        pnlPago.add(txtNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 79, 139, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del Titular");
        pnlPago.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 45, 139, 24));

        txtNumeroT.setText("NUMER");
        txtNumeroT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroTMouseClicked(evt);
            }
        });
        txtNumeroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTActionPerformed(evt);
            }
        });
        txtNumeroT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTKeyTyped(evt);
            }
        });
        pnlPago.add(txtNumeroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 153, 139, 40));

        jLabel2.setText("Número de Tarjeta");
        pnlPago.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 119, 139, 24));

        jLabel4.setText("Fecha de Expiración");
        pnlPago.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 119, 136, 24));

        txtCS.setText("COD");
        txtCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCSMouseClicked(evt);
            }
        });
        txtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSActionPerformed(evt);
            }
        });
        txtCS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCSKeyTyped(evt);
            }
        });
        pnlPago.add(txtCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 237, 139, 30));

        cmbTtarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Visa", "MasterCard", "AMERICAN " }));
        cmbTtarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTtarjetaMouseClicked(evt);
            }
        });
        pnlPago.add(cmbTtarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 139, 30));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        pnlPago.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 310, -1, -1));

        txtMes.setText("MES");
        txtMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesMouseClicked(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        pnlExpi.add(txtMes);

        jLabel3.setText("/");
        pnlExpi.add(jLabel3);

        txtAno.setText("ANO");
        txtAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnoMouseClicked(evt);
            }
        });
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoKeyTyped(evt);
            }
        });
        pnlExpi.add(txtAno);

        pnlPago.add(pnlExpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 153, 136, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/mastercard.jpeg"))); // NOI18N
        pnlPago.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jPanel1.add(pnlPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Panel de pago");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/americanexpress.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/visa.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTActionPerformed
        txtNombreT.setText("");
    }//GEN-LAST:event_txtNombreTActionPerformed

    private void txtNombreTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreTKeyTyped

    private void txtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSActionPerformed
        txtCS.setText("");
    }//GEN-LAST:event_txtCSActionPerformed

    private void txtNumeroTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroTKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoKeyTyped

    private void txtCSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCSKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCSKeyTyped

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        FileOutputStream fbs;
        java.util.Date an = new Date();

        datosg();
        int t = cmbTtarjeta.getSelectedIndex();
        datos[4] = cmbTtarjeta.getItemAt(t);
        String vali[] = new String[2];
        vali[0] = txtMes.getText();
        vali[1] = txtAno.getText();
        fecha = Integer.parseInt(vali[0]);
        ano = Integer.parseInt(vali[1]);
        datos[2] = fecha + "/" + ano;

        String nTarj = txtNumeroT.getText();

        //Validación de numero de tarjeta según empresa
        if (t == 1 && !(nTarj.startsWith("4"))) {
            showMessageDialog(this, "Error 29: La tarjeta Visa debe empezar con el dígito 4");
            return;
        } else if (t == 2 && !(nTarj.startsWith("5"))) {
            showMessageDialog(this, "Error 27: La tarjeta Master Card debe empezar con el dígito 5");
            return;
        } else if (t == 3 && !(nTarj.startsWith("3"))) {
            showMessageDialog(this, "Error 28: La tarjeta American Express debe empezar con el dígito 3");
            return;
        }
        if (t == 0 || datos[0].length() < 5 || datos[1].length() < 16 || datos[2].length() < 4 || datos[3].length() < 3 || fecha < 0 && fecha > 12 || ano < 21) {

            showMessageDialog(this, "Error verifica que todos los campos esten llenos correctamente");
            return;

        } else {

            try {
                fbs = new java.io.FileOutputStream("ListadePagos.tsp");
                java.io.DataOutputStream fds = new java.io.DataOutputStream(fbs);
                for (int i = 0; i < 5; i++) {
                    fds.writeUTF(datos[i]);
                }
                fds.writeUTF("\n");
                fds.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PaneldePago.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PaneldePago.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String exp = Integer.parseInt(txtMes.getText().trim()) + "/" + Integer.parseInt(txtAno.getText().trim());
        PanelCuenta.cuenta.setTarjeta(new clases.Tarjeta(txtNombreT.getText().trim(), txtNumeroT.getText().trim(), exp, Integer.parseInt(txtCS.getText().trim())));
        showMessageDialog(this, "Datos ingresados correctamente \n Ya puede cerrar esta ventana");

    }//GEN-LAST:event_btnPagarActionPerformed

    private void cmbTtarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTtarjetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTtarjetaMouseClicked

    private void txtNumeroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTActionPerformed
        txtNumeroT.setText("");
    }//GEN-LAST:event_txtNumeroTActionPerformed

    private void txtNombreTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTMouseClicked
        txtNombreT.setText("");
    }//GEN-LAST:event_txtNombreTMouseClicked

    private void txtNumeroTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroTMouseClicked
        txtNumeroT.setText("");
    }//GEN-LAST:event_txtNumeroTMouseClicked

    private void txtCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCSMouseClicked
        txtCS.setText("");
    }//GEN-LAST:event_txtCSMouseClicked

    private void txtMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesMouseClicked
        txtMes.setText("");
    }//GEN-LAST:event_txtMesMouseClicked

    private void txtAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnoMouseClicked
        txtAno.setText("");
    }//GEN-LAST:event_txtAnoMouseClicked

    private void datosg() {

        datos[0] = txtNombreT.getText();
        datos[1] = txtNumeroT.getText();

        datos[3] = txtCS.getText();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaneldePago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaneldePago().setVisible(true);
            }
        });
    }
    String datos[] = new String[5];

    int fecha = 0;
    int ano = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cmbTtarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlExpi;
    private javax.swing.JPanel pnlPago;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCS;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombreT;
    private javax.swing.JTextField txtNumeroT;
    // End of variables declaration//GEN-END:variables
}
