/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import javax.swing.JOptionPane.*;
import java.awt.Point;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Hydra
 */
public class PanelDesign extends javax.swing.JPanel {

    private Point puntoInicial;

    /**
     * Creates new form PanelDesign
     */
    public PanelDesign() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        imgCamisa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        cmbLogo = new javax.swing.JComboBox<>();
        pnlColor = new javax.swing.JPanel();
        lblColor = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        pnlTipo = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnDiseñar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(122, 108, 105));
        setLayout(new java.awt.GridBagLayout());

        imgCamisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/kamisama.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(imgCamisa, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/letras.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(jLabel1, gridBagConstraints);

        pnlOpciones.setLayout(new javax.swing.BoxLayout(pnlOpciones, javax.swing.BoxLayout.Y_AXIS));

        pnlLogo.setBackground(new java.awt.Color(153, 153, 153));
        pnlLogo.setPreferredSize(new java.awt.Dimension(120, 30));

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Logo");
        lblLogo.setPreferredSize(new java.awt.Dimension(120, 20));
        pnlLogo.add(lblLogo);

        cmbLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbLogo.setForeground(new java.awt.Color(102, 102, 102));
        cmbLogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Power Rangers", "Pokemon", "BTS" }));
        cmbLogo.setPreferredSize(new java.awt.Dimension(120, 30));
        cmbLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLogoActionPerformed(evt);
            }
        });
        pnlLogo.add(cmbLogo);

        pnlOpciones.add(pnlLogo);

        pnlColor.setBackground(new java.awt.Color(153, 153, 153));
        pnlColor.setPreferredSize(new java.awt.Dimension(120, 30));

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColor.setText("Color");
        lblColor.setPreferredSize(new java.awt.Dimension(120, 20));
        pnlColor.add(lblColor);

        cmbColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbColor.setForeground(new java.awt.Color(102, 102, 102));
        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Azul", "Rojo", "Verde", "Amarillo" }));
        cmbColor.setPreferredSize(new java.awt.Dimension(120, 30));
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });
        pnlColor.add(cmbColor);

        pnlOpciones.add(pnlColor);

        pnlTipo.setBackground(new java.awt.Color(153, 153, 153));
        pnlTipo.setPreferredSize(new java.awt.Dimension(120, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo");
        lblTipo.setPreferredSize(new java.awt.Dimension(120, 20));
        pnlTipo.add(lblTipo);

        cmbTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(102, 102, 102));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Camisa", "Playera", "Sueter" }));
        cmbTipo.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlTipo.add(cmbTipo);

        btnDiseñar.setText("¡Diseñalo!");
        btnDiseñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiseñarActionPerformed(evt);
            }
        });
        pnlTipo.add(btnDiseñar);

        pnlOpciones.add(pnlTipo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlOpciones, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLogoActionPerformed
        
       
    }//GEN-LAST:event_cmbLogoActionPerformed

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColorActionPerformed

    private void btnDiseñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiseñarActionPerformed
         if (cmbLogo.getSelectedIndex()<1)
       {
           showMessageDialog(this,"Por favor, seleccione un logo");
       }
         if (cmbColor.getSelectedIndex()<1)
       {
           showMessageDialog(this,"Por favor, seleccione un color");
       }
         if (cmbTipo.getSelectedIndex()<1)
       {
           showMessageDialog(this,"Por favor, seleccione un tipo");
       }
    }//GEN-LAST:event_btnDiseñarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiseñar;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbLogo;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel imgCamisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlTipo;
    // End of variables declaration//GEN-END:variables

    private void setState(int ICONIFIED) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private class puntoInicial {

        public puntoInicial() {
        }
    }
}
