/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Hydra
 */
public class PanelCompra extends javax.swing.JPanel {

    /**
     * Creates new form PanelCompra
     */
    public PanelCompra() {
        initComponents();
        lblNick.setText(PanelCuenta.cuenta.getNickName());
        lblNombre.setText(PanelCuenta.cuenta.getUsuario().getNombre());
        lblDireccion.setText(PanelCuenta.cuenta.getUsuario().getDireccion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenido = new javax.swing.JPanel();
        Foto = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacompras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(122, 108, 105));
        setLayout(new java.awt.BorderLayout());

        PanelContenido.setBackground(new java.awt.Color(122, 108, 105));
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/iconousuario.png"))); // NOI18N
        Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoMouseClicked(evt);
            }
        });
        PanelContenido.add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 220, 220));

        lblNick.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNick.setForeground(new java.awt.Color(255, 255, 255));
        lblNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNick.setText("Nick");
        PanelContenido.add(lblNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 5, 122, 39));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        PanelContenido.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 54, 122, 39));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccion.setText("Direccion");
        PanelContenido.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 103, 122, 39));

        tablacompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Id"
            }
        ));
        jScrollPane2.setViewportView(tablacompras);

        PanelContenido.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 235, 613, 154));
        PanelContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 130));

        add(PanelContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoMouseClicked
        /*jlabe
        rsscalelabel.RSScaleLabel.setScaleLabel(fotoperfil,fc.getSelectedFile().toString()); */
    }//GEN-LAST:event_FotoMouseClicked
   

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tablacompras;
    // End of variables declaration//GEN-END:variables

    private void setState(int ICONIFIED) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
