/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import excepciones.ExVacio;
import javax.swing.JFileChooser;
import javax.swing.*;
import javax.swing.JOptionPane.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/**
 *
 * @author Hydra
 */
public class PanelCuenta extends javax.swing.JPanel {
    
    public static clases.Cuenta cuenta;
    public static int index;

    /**
     * Creates new form PanelCuenta
     */
    public PanelCuenta() {
        initComponents();
        txtNick.setText(cuenta.getNickName());
        txtNombre.setText(cuenta.getUsuario().getNombre());
        txtDireccion.setText(cuenta.getUsuario().getDireccion());
        txtCorreo.setText(cuenta.getUsuario().getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenido = new javax.swing.JPanel();
        fotoperfil = new javax.swing.JLabel();
        Nick = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(122, 108, 105));
        setLayout(new java.awt.BorderLayout());

        PanelContenido.setBackground(new java.awt.Color(122, 108, 105));
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoperfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/images/iconousuario.png"))); // NOI18N
        PanelContenido.add(fotoperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 182, -1));

        Nick.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Nick.setForeground(new java.awt.Color(255, 255, 255));
        Nick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nick.setText("Nickname:");
        PanelContenido.add(Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 238, 121, 39));

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre:");
        PanelContenido.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 287, 121, 39));

        Direccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direccion.setText("Direccion:");
        PanelContenido.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 336, 121, 39));

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo:");
        PanelContenido.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 385, 121, 39));

        txtNick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PanelContenido.add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 241, 182, 33));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        PanelContenido.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 182, 33));

        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PanelContenido.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 339, 182, 33));

        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PanelContenido.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 388, 182, 33));

        btnCambiar.setText("Cambiar foto");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        PanelContenido.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 139, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        PanelContenido.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 434, 97, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelContenido.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 434, 75, -1));
        PanelContenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 120, 120));

        add(PanelContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        JFileChooser fc= new JFileChooser();
        fc.setDialogTitle("Buscar Imagen");
        
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            
        
        rsscalelabel.RSScaleLabel.setScaleLabel(fotoperfil,fc.getSelectedFile().toString());    
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (campoVacio(txtNick)) {
            return;
        }
        if (campoVacio(txtNombre)) {
            return;
        }
        if (campoVacio(txtDireccion)) {
            return;
        }
        if (campoVacio(txtCorreo)) {
            return;
        }
        datos.EscrituraTxt es = new datos.EscrituraTxt();
        es.modificarCuenta(cuenta, index);
        Limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
      char c= evt.getKeyChar();
      if((c<'a'||c>'z') && (c<'A'||c>'Z')){
          evt.consume();
      }
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private boolean campoVacio(JTextField jtf) {
        try {
            contenido(jtf);
            return false;
        } catch (ExVacio ev) {
            showMessageDialog(this, ev.getMessage(), "Error en entrada", JOptionPane.ERROR_MESSAGE);
            jtf.requestFocus();
            return true;
        }
    }
    private void contenido(JTextField jtf) throws ExVacio {
        if (jtf.getText().trim().equals("")) {
            throw new ExVacio("Por favor llene todos los campos correctamente");
        }
    }
    
    public void Limpiar(){
        txtNick.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Nick;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fotoperfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
