/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Venta;
import excepciones.ExVacio;

/**
 *
 * @author Hydra
 */
public class PanelInfoVentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentas
     */
    public PanelInfoVentas() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuPop = new javax.swing.JPopupMenu();
        itEditarVenta = new javax.swing.JMenuItem();
        itEditarRegistro = new javax.swing.JMenuItem();
        itBorrarVenta = new javax.swing.JMenuItem();
        itBorrarRegistro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itCobertura = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        itEditarVenta.setText("Editar venta");
        itEditarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itEditarVentaActionPerformed(evt);
            }
        });
        menuPop.add(itEditarVenta);

        itEditarRegistro.setText("Editar registro");
        menuPop.add(itEditarRegistro);

        itBorrarVenta.setText("Eliminar venta");
        menuPop.add(itBorrarVenta);

        itBorrarRegistro.setText("Borrar Registro");
        menuPop.add(itBorrarRegistro);
        menuPop.add(jSeparator1);

        itCobertura.setText("Ver cobertura");
        menuPop.add(itCobertura);

        setBackground(new java.awt.Color(122, 108, 105));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setLayout(new java.awt.GridBagLayout());

        tblVentas.setAutoCreateRowSorter(true);
        tblVentas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Fecha", "Folio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentas.setComponentPopupMenu(menuPop);
        jScrollPane1.setViewportView(tblVentas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.ipady = 300;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void itEditarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itEditarVentaActionPerformed
        
        //tblVentas.setValueAt(cmbUsuario.getSelectedItem(), seleccion, 0);
        //tblVentas.setValueAt(cmbProducto.getSelectedItem(), seleccion, 1);
        //tblVentas.setValueAt(date, seleccion, 2);
        //tblVentas.setValueAt(txtFolio.getText().trim(), seleccion, 3);
        //tblVentas.setValueAt(cmbGarantia.getSelectedItem(), seleccion, 4);
        //tblVentas.setValueAt(chkExpirado.isSelected(), seleccion, 5);
        //tblVentas.setValueAt(chkCobrado.isSelected(), seleccion, 6);
    }//GEN-LAST:event_itEditarVentaActionPerformed

    private void llenarTabla() {
        ventas = lt.obtenerVenta();
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblVentas.getModel();
        for (Venta v : ventas) {
            try {
                dtm.addRow(new Object[]{v.getProducto().getNombre(), v.getFecha(), v.getFolio()});
            } catch (NullPointerException e) {
                break;
            }

        }
    }

    private void valorCombo(javax.swing.JComboBox<String> combo, String val) {
        for (int i = 1; i < combo.getItemCount(); i++) {
            if (val.equalsIgnoreCase(combo.getItemAt(i))) {
                combo.setSelectedIndex(i);
                break;
            }
        }
    }

    private void validarCombo(javax.swing.JComboBox combo) throws ExVacio {
        if (combo.getSelectedIndex() == 0) {
            combo.requestFocus();
            throw new ExVacio("No se ha seleccionado una opcion");
        }
    }

    private int seleccion;
    private clases.Venta[] ventas;
    private final datos.Escritura es = new datos.EscrituraTxt();
    private final datos.Lectura lt = new datos.LecturaTxt();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itBorrarRegistro;
    private javax.swing.JMenuItem itBorrarVenta;
    private javax.swing.JMenuItem itCobertura;
    private javax.swing.JMenuItem itEditarRegistro;
    private javax.swing.JMenuItem itEditarVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu menuPop;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
